// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EvaluateCandidate(arg1, arg2) {
  return window['go']['main']['App']['EvaluateCandidate'](arg1, arg2);
}

export function OpenResumeFile(arg1) {
  return window['go']['main']['App']['OpenResumeFile'](arg1);
}

export function RunMatch(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RunMatch'](arg1, arg2, arg3, arg4);
}

export function SelectJDFile() {
  return window['go']['main']['App']['SelectJDFile']();
}

export function SelectOutputFile() {
  return window['go']['main']['App']['SelectOutputFile']();
}

export function SelectResumesFolder() {
  return window['go']['main']['App']['SelectResumesFolder']();
}
