// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {matcher} from '../models';

export function EvaluateCandidate(arg1:string,arg2:string):Promise<matcher.ResumeAnalysis>;

export function OpenResumeFile(arg1:string):Promise<void>;

export function RunMatch(arg1:string,arg2:string,arg3:number,arg4:string):Promise<matcher.Output>;

export function SelectJDFile():Promise<string>;

export function SelectOutputFile():Promise<string>;

export function SelectResumesFolder():Promise<string>;
